### PR TITLE
reuse compliance

### LINKED ISSUE #310: [rl-reuse_tool-4] Violation against OSS Rules of Play
A violation against the OSS Rules of Play has been detected.

Rule ID: rl-reuse_tool-4
Explanation: Is it compliant with REUSE rules? **No**

Find more information at: https://sap.github.io/fosstars-rating-core/oss_rules_of_play_rating.html

### PR DESCRIPTION
**Pull request by ajinkyapatil8190**
fixes #310 #309 , please add your email id in the upstream contact.

### CODE REVIEW

**Review by strekm — APPROVED** [review]
/moew

**Review by nataliasitko — DISMISSED** [review]

**Comment by strekm** [comment]
@ajinkyapatil8190 please sign cla and resolve conflicts

**Comment by TorstenD-SAP** [comment]
Hi @ajinkyapatil8190, it looks like you haven't signed the CLA (see [this](https://github.com/CLAassistant)). Can you please sign the CLA in order to get this merged.

**Comment by ajinkyapatil8190** [comment]
Done 👍

**Comment by kolodziejczak** [comment]
@ajinkyapatil8190 still can't be merged because of conflicts, could you resolve them?

**Pull request merged**
